# Site settings
title: MuLab Library
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  images:
    title: Images
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: 
    layout: post
email: 17ap87@queensu.ca
description: >
  Work in progress...
baseurl:
url:
twitter_username: alice_petrov_
github_username:  alicepetrov

# Build settings
markdown: kramdown
permalink: pretty
