# Site settings
title: MuLab Library
email: 17ap87@queensu.ca
description: >
  Work in progress...
baseurl:
url:
twitter_username: alice_petrov_
github_username:  alicepetrov

# Build settings
markdown: kramdown
permalink: pretty
